version: '3'

services:

    php:
        container_name: ${PROJECT_NAME}_php
        networks:
            - projects_${PROJECT_NAME}
        build:
            context: ./docker/php
        ports:
            - 9000:9000
        volumes:
            - appdata:/var/www
            - ./source:/var/www/html/projects/ce243:cached
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
 
    nginx:
        container_name: ${PROJECT_NAME}_nginx
        networks:
            - projects_${PROJECT_NAME}
        image: nginx:1.14-alpine
        ports:
            - 80:80
        volumes:
            - ./source:/var/www/html/projects/ce243:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/nginx.conf:/var/www/html/projects/nginx_ce243.conf
        depends_on:
            - php
 
    db:
        container_name: ${PROJECT_NAME}_mariadb
        networks:
            - projects_${PROJECT_NAME}
        image: mariadb:10.4
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            
    redis:
        container_name: ${PROJECT_NAME}_redis
        networks:
            - projects_${PROJECT_NAME}
        image: redis:latest

    rabbitmq:
        container_name: ${PROJECT_NAME}_rabbitmq
        networks:
            - projects_${PROJECT_NAME}
        image: rabbitmq:3-management
        ports:
            - "15672:15672"
            - "5672:5672"

    elasticsearch:
        container_name: ${PROJECT_NAME}_elasticsearch
        networks:
            - projects_${PROJECT_NAME}
        image: elasticsearch:7.6.2
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            "discovery.type": "single-node" 

    phpmyadmin:
        container_name: ${PROJECT_NAME}_phpmyadmin
        networks:
            - projects_${PROJECT_NAME}
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: "db"
            PMA_PORT: "3306"
            PMA_USER: "root" 
            PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
    appdata:
    dbdata:

networks:
    projects_ce243:
